// <auto-generated />
using HotelListing.API.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListing.API.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    partial class HotelListingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelListing.API.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CountryCode = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = "2",
                            CountryCode = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = "3",
                            CountryCode = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = "4",
                            CountryCode = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = "5",
                            CountryCode = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = "6",
                            CountryCode = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = "7",
                            CountryCode = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = "8",
                            CountryCode = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = "9",
                            CountryCode = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = "10",
                            CountryCode = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = "11",
                            CountryCode = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = "12",
                            CountryCode = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = "13",
                            CountryCode = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = "14",
                            CountryCode = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = "15",
                            CountryCode = "ZA",
                            Name = "South Africa"
                        });
                });

            modelBuilder.Entity("HotelListing.API.Domain.Entities.Hotel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Address = "1 South County Road, Palm Beach, Florida, USA",
                            CountryId = "3",
                            Name = "The Breakers Palm Beach",
                            Rating = "4.8"
                        },
                        new
                        {
                            Id = "2",
                            Address = "3-3-1 Nishi-Shinjuku, Shinjuku-ku, Tokyo, Japan",
                            CountryId = "14",
                            Name = "Park Hyatt Tokyo",
                            Rating = "4.9"
                        },
                        new
                        {
                            Id = "3",
                            Address = "Motu Tehotu, Bora Bora, French Polynesia",
                            CountryId = "6",
                            Name = "Four Seasons Resort Bora Bora",
                            Rating = "5.0"
                        },
                        new
                        {
                            Id = "4",
                            Address = "Auchterarder, Perthshire, Scotland",
                            CountryId = "5",
                            Name = "Gleneagles Hotel",
                            Rating = "4.7"
                        },
                        new
                        {
                            Id = "5",
                            Address = "Gütschstrasse 8, Lucerne, Switzerland",
                            CountryId = "5",
                            Name = "Hotel Château Gütsch",
                            Rating = "4.9"
                        },
                        new
                        {
                            Id = "6",
                            Address = "32 Liangmaqiao Road, Chaoyang District, Beijing, China",
                            CountryId = "8",
                            Name = "頤和園洲際酒店 (InterContinental Beijing Sanlitun)",
                            Rating = "4.8"
                        },
                        new
                        {
                            Id = "7",
                            Address = "Palm Jumeirah, Dubai, United Arab Emirates",
                            CountryId = "6",
                            Name = "One&Only The Palm",
                            Rating = "4.7"
                        },
                        new
                        {
                            Id = "8",
                            Address = "Nybrogatan 11, Stockholm, Sweden",
                            CountryId = "11",
                            Name = "Ett Hem Stockholm",
                            Rating = "5.0"
                        },
                        new
                        {
                            Id = "9",
                            Address = "1 Cathedral Square, Perth, Australia",
                            CountryId = "6",
                            Name = "COMO The Treasury",
                            Rating = "4.9"
                        },
                        new
                        {
                            Id = "10",
                            Address = "Salihdede Mahallesi Kaplankaya Turkey",
                            CountryId = "11",
                            Name = "Six Senses Kaplankaya",
                            Rating = "4.8"
                        });
                });

            modelBuilder.Entity("HotelListing.API.Domain.Entities.Hotel", b =>
                {
                    b.HasOne("HotelListing.API.Domain.Entities.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelListing.API.Domain.Entities.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
